language: node_js
node_js:
- "10"

branches:
  only:
  - production

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

install:
  - npm install

script:
  - npm run build

deploy:
  provider: script
  script: "npm publish"
  skip_cleanup: true
  on:
    branch: production
