language: node_js
node_js:
- "node"

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

before_deploy: "npm i"

deploy:
  provider: script
  script: "npm build && npm publish"
  skip_cleanup: true
  on:
    branch: production
