/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface LearnMathBasicComponent {
    'max': number;
    'min': number;
    'type': string;
  }
  interface LearnMathBasicComponentAttributes extends StencilHTMLAttributes {
    'max'?: number;
    'min'?: number;
    'type'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'LearnMathBasicComponent': Components.LearnMathBasicComponent;
  }

  interface StencilIntrinsicElements {
    'learn-math-basic-component': Components.LearnMathBasicComponentAttributes;
  }


  interface HTMLLearnMathBasicComponentElement extends Components.LearnMathBasicComponent, HTMLStencilElement {}
  var HTMLLearnMathBasicComponentElement: {
    prototype: HTMLLearnMathBasicComponentElement;
    new (): HTMLLearnMathBasicComponentElement;
  };

  interface HTMLElementTagNameMap {
    'learn-math-basic-component': HTMLLearnMathBasicComponentElement
  }

  interface ElementTagNameMap {
    'learn-math-basic-component': HTMLLearnMathBasicComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
